#!/usr/bin/env bash
# Using Secure Copy (scp) to transfer file from client to
#  the home directory on the server

if [ "$#" -eq 3 ]
then
    scp -o StrictHostKeyChecking=no "$1" "$3@$2":~/
elif [ "$#" -eq 4 ]
then
    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~/
else
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
