#!/usr/bin/env bash
# Installing nginx on server and serving a basic html

# Install NginX server
sudo apt-get update
sudo apt-get -y install nginx
# Allow Nginx through the firewall
# sudo ufw enable (may disrupt SSH connection if not allowed)
sudo ufw allow 'Nginx HTTP'
# Write "Hello World!" to one of the default served htmls
sudo chmod 666 /var/www/html/index.nginx-debian.html
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo chmod 644 /var/www/html/index.nginx-debian.html
# Refresh the caches and pick up new changes
sudo service nginx restart
